#! /bin/sh
PATHS_FILE="/etc/btrsnap_paths.conf"
DESTINATION="/btrfs_snapshots"
VERSION="btrsnap v0.3"

if [ ! -f "$PATHS_FILE" ]; then
    sudo touch "$PATHS_FILE"
fi

add_subvolume(){
    if [ ! -d "$1" ]; then
        echo "Error: Subvolume path does not exist!"
        return
    fi
    exists=0
    while IFS= read -r subvolume; do
	if [ $subvolume = "$(realpath "$1")" ]; then
	    exists=1
	fi
    done < "$PATHS_FILE"
    if [ $exists -eq 0 ]; then
	echo "$(realpath $1)" >> "$PATHS_FILE"
	[ $? -eq 0 ] && echo "Subvolume $(basename $1) added to config"
	[ $? -eq 1 ] && echo "Permission denied"
    else
	echo "Subvolume $(basename $1) already exists!"
    fi
    
}

create_dest(){
    if [ ! -d "$DESTINATION" ]; then
        sudo mkdir "$DESTINATION"
    fi
}

snap_from_conf(){
    create_dest
    while IFS= read -r subvolume; do
	snap "$subvolume"
    done < "$PATHS_FILE"
}

snap(){
    create_dest
    if [ "$1" = "/" ]; then
	subvolume_name=root
    else
	subvolume_name=$(basename $1)
    fi
    if [ ! -d "$DESTINATION/$subvolume_name" ]; then
	sudo mkdir $DESTINATION/$subvolume_name
    fi
    snapshot_name=""$subvolume_name"_$(date +%Y-%m-%d_%H-%M-%S)"
    sudo btrfs subvolume snapshot -r $1 $DESTINATION/$subvolume_name/$snapshot_name
}

remove_path(){
    sudo sed -in "/\/$1$/d" $PATHS_FILE
}

delete_oldest(){
    duration=7
    delete="$(date --date=""$duration" days ago" +"%Y")-$(date --date=""$duration" days ago" +"%m")-$(date --date=""$duration" days ago" +"%d")_$(date --date=""$duration" days ago" +"%H")-$(date --date=""$duration" days ago" +"%M")-$(date --date=""$duration" days ago" +"%S")"
    echo $delete
    for volume in "$DESTINATION/*/" ; do
	for snapshot in "$volume/*/" ; do
	    if [ "$(basename $snapshot)" /< "$delete" ]; then
		echo "$(basename $snapshot)"
	    fi
	    echo $snapshot
	    echo $delete
	done
    done
}

delete_snapshot(){
    sudo btrfs subvolume delete $1
}

list_snapshots(){
    if [ -z "$1" ]; then
       echo "Specify subvolume"
       return
    elif [ ! -d "$DESTIINATION/$1" ]; then
    echo "Subvolume $1 has no snapshots"
    return
    fi
    for s in $(ls "$DESTINATION/$1") ; do
	echo "$s"
    done
}

list_subvolumes(){
    for s in $(ls "$DESTINATION") ; do
	echo "$s"
    done
}

list_paths(){
    cat $PATHS_FILE
}

print_version(){
    echo "$VERSION"
}

help(){
    echo "usage: btrsnap [option] [args]"
    echo ""
    echo "options:"
    echo "   -s               takes snapshot of all subvolumes in config"
    echo "   -t <subvolume>   takes snapshots of specific subvolume"
    echo "   -e               specify destination of snapshot"
    echo "   -a <path>        adds subvolume to config"
    echo "   -r <subvolume>   removes subvolume path from config"
    echo "   -d <snapshot>    alias to btrfs subvolume delete"
    echo "   -h               prints this message"
    echo "   -n <subvolume>   lists taken snapshots"
    echo "   -p               lists all paths in config"
    echo "   -l               lists subvolumes that has snapshots taken"
    echo "   -v               prints btrsnap version"
    echo ""
    echo "btrfs subvolumes must be created then you can add its path"
    echo "do sudo btrfs subvolume create <subvolume> to create a btrfs subvolume"
}

invalid_input(){
    echo "unrecongnized option"
    echo "do btrfs -h for help"
}

while getopts ":a:r:d:n:slpxvhe:t:" option; do
    case $option in
	s)
	    snap_from_conf
	    ;;
	a)
	    add_subvolume "$OPTARG"
	    ;;
	r)
	    remove_path "$OPTARG"
	    ;;
	d)
	    delete_snapshot "$OPTARG"
	    ;;
	n)
	    list_snapshots "$OPTARG"
	    ;;
	t)
	    snap "$OPTARG"
	    ;;
	l)
	    list_subvolumes
	    ;;
	p)
	    list_paths
	    ;;
	v)
	    print_version
	    ;;
	h)
	    help
	    ;;
	e)
	    DESTINATION="$(realpath "$OPTARG")/btrfs_snapshots"
	    ;;
	
	x)
	    delete_oldest
	    ;;
	*)
	    invalid_input
	    ;;
    esac
done
